app/assets/stylesheets/passengers.scss, app/controllers/passengers_controller.rb, app/views/passengers/index.haml
Closes #30.
Default is show both permanent & temporary, and hide inactive (show only active). You can select whether to see temporary, permanent, or both; and then (separately) whether to show inactive.
Previously was just one radio button, which didn't allow for combining the filters.
=> Refactor passenger filtering

app/assets/stylesheets/mobility_devices.scss, app/controllers/mobility_devices_controller.rb, app/models/mobility_device.rb, app/views/layouts/_navbar.haml, app/views/mobility_devices/_form.haml, app/views/mobility_devices/edit.haml, app/views/mobility_devices/index.haml, app/views/mobility_devices/new.haml, config/routes.rb, db/migrate/20170829130516_add_needs_longer_rides_to_mobility_devices.rb, db/migrate/20170829132804_remove_lift_ramp_from_mobility_devices.rb, db/schema.rb
Closes #47.
Renamed (effectively) `lift_ramp` to `needs_longer_rides` for clarity.
=> Manage mobility devices

app/models/passenger.rb, coverage/.last_run.json, spec/models/passenger_spec.rb
We effectively were, by enforcing this format validation on blank strings.
=> Don't require a SPIRE

app/assets/javascripts/input_disable.js, app/assets/stylesheets/doc_note.scss, app/assets/stylesheets/passengers.scss, app/controllers/passengers_controller.rb, app/helpers/passengers_helper.rb, app/views/passengers/_form.html.haml, spec/features/passenger_management_spec.rb
This PR also adds a check for the presence of a passengers note before updating passenger_note_params.
=> Disable perm. passenger fields on page load 

config/database.yml.example, db/schema.rb
utf8 is garbage. 
See https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434
=> Use utf8mb4 as the default encoding

config/deploy/production.rb
Uses configuration for `app3` to connect to `app4`.
=> Typo in production config

coverage/.last_run.json, spec/system/passenger_management_spec.rb, spec/system/user_management_spec.rb
These tests failed when I decided destroying a user should be a button rather than a link.
In fixing it, I realized that the xpath notation is nearly impenetrable to me, and it doesn't really reflect how a "real person" would find what thing to click on. Instead of finding by `href`, let's find the "Destroy" that's in the same row as the user's name.
=> Xpath removal

app/helpers/passengers_helper.rb, app/views/passengers/archived.html.haml, app/views/passengers/index.haml, coverage/.last_run.json
Closes #188.
In looking into it, it seems like there are cases where DataTables thinks the data source is something other than the DOM (?) A fix I found was to explicitly put `data-type="@data-sort"` on the header. But... if we're going to do that, why not just use `data-type="date"`? Sorts like a dream.
=> Just tell DataTables it's a date

app/helpers/application_helper.rb, app/views/passengers/index.haml
by providing some screen-reader-only content.  As a side-effect, DataTables can sort by said content, making the `data-sort` attribute no longer needed.
=> Make the glyphs a bit more accessible

app/controllers/feedback_controller.rb, app/controllers/users_controller.rb, app/models/feedback.rb, app/models/user.rb, app/views/feedback/index.haml, app/views/users/show.haml, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/routes.rb, coverage/.last_run.json, spec/models/feedback_spec.rb, spec/system/feedback_submission_spec.rb
People with logins to the site can click the link to see who submitted the feedback. Everyone else will have to use the Rails console.
=> Put a pseudo-anonymous signature in the GH issues

db/seeds.rb, spec/factories/passengers.rb
you don't have to do after_create hooks to have an association with
an object. and let's keep non-essential associations or attributes
to traits.
=> this has been bothering me.

app/controllers/passengers_controller.rb
Noticed a bunch of queries scrolling by on the index page thought it
could use a small optimization.
Reduces the "ActiveRecord" time to render the index on my machine down
from 30ms to 5ms (wooo)
=> Include some relations to reduce N+1s

db/seeds.rb, spec/factories/eligibility_verifications.rb, spec/factories/passengers.rb, spec/helpers/passengers_helper_spec.rb, spec/models/passenger_spec.rb, spec/system/passenger_archive_spec.rb, spec/system/passenger_filters_spec.rb, spec/system/passenger_key_spec.rb
For example, if passenger has an association :eligibility_verification
and eligibility verification has an association with passenger,
creating a passenger with an eligibility verification will create a
second passenger.
Tests pass and objects are properly related to each other with no
extras.
=> Use after_create blocks to associate certain objects in FactoryBot

app/mailers/passenger_mailer.rb, app/models/passenger.rb, app/views/passenger_mailer/notify_archived.haml
closes #156
Added automatic emailing behavior when a passenger is archived.
As it stands the mailer is specific to passenger mail. I chose this over a more general class; in my mind it allows for more organization/scalability in the future with the downsides mainly being some unnecessary categorization.
The email is sent from the Passenger model, within the toggle_archived_status method. I couldn't really find an elegant way to implement sending the email while preserving the original return value. I took the route of making the changes uglier in favor of readability.
=> Backend mailing code written, placeholder email template given

app/controllers/passengers_controller.rb, app/views/passengers/show.haml, coverage/.last_run.json
Closes #209 
As it was, the controller method was trying to assign the registerer by assigning `.registered_by` as the user's ActiveRecord object, when `.registered_by` is actually the foreign_key id column. 
As it was, displaying a passenger also trying to display the object string format (<ActiveRecord: ...>. Now it correctly displays the dispatcher's name.
=> Creating new passenger now correctly records the registerer

app/controllers/log_controller.rb, app/views/log/index.haml, coverage/.last_run.json
Closes #175 
The server was 500ing due to some improper render calls on error, which I just combined with the success redirect since they serve the same purpose.
Also required the edit text box to have text on an html level. Now a user shouldn't be able to submit a bad request and if a bad request somehow happens, it will flash an error and not silently fail.
=> Fixed error handling for dispatch logs

spec/models/passenger_spec.rb
The method under test is using `Date` database fields, but `14.days.from_now` is an `ActiveSupport::TimeWithZone`. The business days gem also takes into account operating _hours_, so "*Passenger rides\_expire doctors note present the doctors note is not expired returns three business days after the expiration date of the note*" fails when the specs are run after 5pm.
This is because, after the business closes for the day,`3.business_days.after(now).to_date` is different than `3.business_days_after(now.to_date)`
=> Calculate ride expiration based only on the date.

spec/models/passenger_spec.rb
This is the same change as #234 
It was reverted in #228, I suspect as a result of an incorrect merge conflict resolution.
=> Calculate ride expiration based only on the date (Again)

app/models/passenger.rb, coverage/.last_run.json, spec/models/passenger_spec.rb
As soon as the passenger is saved, their registration _date_ will be assigned to be `Time.zone.today`, so it doesn't make sense for it to be a date and time before the passenger is saved.
Also, it should be 3 business days after the beginning of today, not the beginning of the day 3 business days from now.
=> Another date fix

spec/models/passenger_spec.rb
This test occasionally fails depending on when it's run. I'm not exactly sure why but it seems `3.business_days.from_now()`  calculates the resulting `ActiveSupport::TimeWithZone` from the wrong time zone.
In the model:
```ruby
def rides_expire
return if permanent?
if eligibility_verification&.expiration_date.present?
return 3.business_days.after(eligibility_verification.expiration_date)
end
return 3.business_days.after(registration_date) if persisted?
3.business_days.after(Time.zone.today)
end
```
=> Fix occasional passenger spec failure

Gemfile.lock
Ugh.
I have a suspicion that this will fail on Travis too, however. Depends on their Ubuntu VMs; we'll see.
=> Update mimemagic again

app/models/passenger.rb
requires_verification? returns false before the call to update.
must set desired status before the SQL insert statement is attempted.
I was able to activate the registration of WHOMEVER, without them having entered the required info. Tricky!
=> validation will not run properly on update

config/deploy.rb, lib/capistrano/tasks/git.rake
As of Git 2.35.2, Git will refuse to use `.git` directories that aren't owned by you. There are security concerns here: that other person could insert hooks, etc. to be run by you. In this case, we don't have a mix of user-privileges; anything one deployer can be forced to do could have just been done by the forcer directly.
Here, we add the repository repo to the deployer's list of "safe" git directories.
This will _eventually_ need to be done on all the rest of our repos, too. But app4 is affected now.
=> Allow git repo directory to be shared among deployers

app/views/layouts/_navbar.haml, config/routes.rb
Noticed that the "Logout" link on the [unauthorized page](https://github.com/umts/st-pax/blob/6c7420cfa434cea084f0bfb3f5db58628076191e/app/views/sessions/unauthenticated.haml#L29) didn't work. This was because that page expected it to be a `DELETE` route. That made more sense to me, so I ended up changing the one logout link that _wasn't_ a `DELETE` route instead.
=> Fix logout link on "unauthorized" page

app/controllers/passengers_controller.rb, config/routes.rb
I think passengers are given a link directly to `/register` but I don't see a reason to give them a 401 if they come right to the root of the site.
=> Add a redirecting route for use with the site root

README.md, app/controllers/passengers_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/helpers/passengers_helper.rb, app/mailers/passenger_mailer.rb, app/views/layouts/application.html.haml, app/views/passenger_mailer/notify_active.haml, app/views/passenger_mailer/notify_archived.haml, app/views/passenger_mailer/notify_pending.haml, app/views/passengers/_policies.html.haml, app/views/passengers/_scheduling_rides_information.html.haml, app/views/passengers/brochure.html.haml, app/views/sessions/subsidiary.html.haml, app/views/sessions/unauthenticated.haml, app/views/users/index.html.haml, config/locales/en.yml, spec/mailers/passenger_mailer_spec.rb
I went the extra step of moving the department, staff, and contact info into the locales file.
This is almost all of #328, but I'm still working on redoing auth on this app in order to allow us to deploy the app at a different URL than st-pax.admin.umass.edu.
=> Replace ST with AVS

contrib/spire-lookup.ps1
Occasionally, folks _are_ still in on-prem AD, but their account is inactive (recently left?) and they've never been synced to Azure AD. In those cases, the "external directory object id" property is missing/null.
=> Update spire-lookup.ps1 to account for null uids

db/migrate/20230922123246_add_spire_unique_indices.rb, db/schema.rb
Turns out that there are a ton of (invalid) Passengers in prod with a `nil` Spire ID. I'm just going to punt on this one given that I _hope_ to be removing that column at some point.
=> Ease up on the passenger index

.rubocop.yml, Gemfile, Gemfile.lock, spec/factories/eligibility_verifications.rb
I _think_ that this is actually a no-op: they're dependencies of rubocop-rspec, which makes me think that that gem uses these two already. But rubocop says, "hey, don't you want to enable these gems?"
=> Enabled rubocop-capybara & rubocop-factory_bot

db/migrate/20240118184517_add_uniqe_indices.rb, db/schema.rb
At the suggestion of rubocop. I _didn't_ do passengers' email or passengers' spire because the production data is too terrible. At least one of these is going away at some point.
=> Added the easy unique indices

Gemfile, Gemfile.lock
We don't need to convert any more erb files at this point.
=> Remove erb2haml

app/views/log_entries/_form.html.haml, app/views/log_entries/index.html.haml
1. Add form namespace for log entries: This changes how the ids for form elements are generated, and prevents
collisions between `for=` values. We had manually done that with the pinned checkbox, but not the text box, leading to some accessibility errors.
2. Change log timestamp from link to span: It seemed weird to me that the timestamp was a "link" that didn't go anywhere.
=> Two small fixes for the dispatch log

app/assets/javascripts/application.js
Happened to have the console open looking for something else and noticed this:
```
Uncaught TypeError: $(...).tooltip is not a function
<anonymous> https://st-pax.admin.umass.edu/assets/application-cf19bfb9219d9fe12d2b48f4d0bc60e9d0fdec7fdcfced4d98fed6722d659808.js:35
dispatch https://st-pax.admin.umass.edu/assets/application-cf19bfb9219d9fe12d2b48f4d0bc60e9d0fdec7fdcfced4d98fed6722d659808.js:2
handle https://st-pax.admin.umass.edu/assets/application-cf19bfb9219d9fe12d2b48f4d0bc60e9d0fdec7fdcfced4d98fed6722d659808.js:2
a https://st-pax.admin.umass.edu/assets/application-cf19bfb9219d9fe12d2b48f4d0bc60e9d0fdec7fdcfced4d98fed6722d659808.js:6
notifyApplicationAfterPageLoad https://st-pax.admin.umass.edu/assets/application-cf19bfb9219d9fe12d2b48f4d0bc60e9d0fdec7fdcfced4d98fed6722d659808.js:22 …
```
=> Fix Bootstrap not modifying jQuery on initial load

app/controllers/mobility_devices_controller.rb
Closes #551 
`MobilityDevicesController#set_device` will now return the standard `ActiveRecord::RecordNotFound` error if the mobility device can't be found. This will render the 404 page in development instead of a blank one. This matches the `PassengersController` and `UsersController`.
=> MobilityDevicesController Returns Correct 404 Error

Gemfile, Gemfile.lock, spec/rails_helper.rb
The contagion of
```
Selenium::WebDriver::Error::UnknownError:
unknown error: unhandled inspector error: {"code":-32000,"message":"Node with given id does not belong to the document"}
```
has spread to this app, I guess. Google hasn't really gotten me much.
=> Add and configure rspec-retry for system tests

config/initializers/new_framework_defaults_7_2.rb
I guess there's a chance our VM could be considered a "memory constrained" environment. I do want to keep an eye on the server for a bit after deployment.
=> Enable yjit

app/controllers/feedback_controller.rb, app/controllers/mobility_devices_controller.rb, app/controllers/passengers_controller.rb, app/controllers/users_controller.rb, spec/requests/mobility_devices_spec.rb
Rack has deprecated it in favor of `:unprocessable_content` (which is the name of the status code in the HTTP spec)
=> Change deprecated `:unprocessable_entity` statuses

Gemfile, Gemfile.lock, spec/models/log_entry_spec.rb
Rails has it built-in, but it turns out we were only using it to set one `created_at` value, which we can just do directly.
=> Remove Timecop gem
