app/assets/javascripts/application.js, app/assets/javascripts/datatables.js, app/assets/stylesheets/application.css, app/assets/stylesheets/passengers.scss, app/controllers/passengers_controller.rb, app/helpers/passengers_helper.rb, app/models/passenger.rb, app/views/passengers/index.haml, db/seeds.rb, package.json, yarn.lock
=> Made color codes

public/401.html
From umts/jobapps.
Closes #13.
=> Add a 401 page

app/controllers/users_controller.rb, app/models/user.rb, app/views/users/_form.html.haml, app/views/users/index.html.haml, app/views/users/show.html.haml, db/migrate/20170821165344_remove_email_from_users.rb, db/schema.rb, spec/factories/users.rb
=> Remove email from users

app/models/passenger.rb, db/migrate/20170823143949_add_missing_attributes_to_passengers.rb, db/schema.rb, lib/tasks/import/passengers.rake
~Closes~ Addresses #27.
Final step in preparing for the data migration will be to make the frontend cope with various kinds of invalid data.
=> Add passenger attributes

app/controllers/sessions_controller.rb, app/models/user.rb, app/views/layouts/_navbar.haml, app/views/log/index.haml
Closes #19.
Turns out, this app is fairly permissive about missing attributes.
=> Handle invalid data

app/assets/stylesheets/users.scss, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/models/user.rb, app/views/layouts/_navbar.haml, app/views/users/_form.html.haml, app/views/users/edit.html.haml, app/views/users/index.html.haml, config/locales/en.yml, config/routes.rb, lib/tasks/import/dispatchers.rake, spec/factories/users.rb
=> User administration

app/controllers/mobility_devices_controller.rb, app/controllers/passengers_controller.rb, app/models/mobility_device.rb, app/views/mobility_devices/_form.haml, app/views/mobility_devices/edit.haml, app/views/mobility_devices/index.haml, app/views/passengers/_form.html.haml, app/views/passengers/index.haml, app/views/passengers/show.haml, db/migrate/20170829182335_change_device_to_name_in_mobility_devices.rb, db/schema.rb, lib/tasks/import/mobility_devices.rake, lib/tasks/import/passengers.rake, spec/factories/mobility_devices.rb
Pending #53, Travis will tell us whether I did this correctly.
=> Change #device to #name on MobilityDevice

app/controllers/users_controller.rb, app/views/users/_form.html.haml, app/views/users/index.html.haml, coverage/.last_run.json, db/migrate/20170831135848_remove_phone_from_users.rb, db/schema.rb, spec/factories/users.rb
=> Remove phone from users

app/assets/javascripts/application.js, app/assets/javascripts/reactivation_warning.js, app/views/passengers/_form.html.haml, package.json, yarn.lock
=> Reactivation warning

Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/production.rb
*  Added Capfile and lib/capistrano/tasks
*  Added gems to Gemfile
*  Changed production server
*  Updated config for Capistrano 3.8+
*  Removed application.yml and Nokogiri related config
May need additional work, but I need something on GitHub to keep working.
=> Capistrano configuration

.travis.yml
=> use travis actual username

app/assets/stylesheets/passengers.scss
=> Underline links

Gemfile, Gemfile.lock, app/controllers/log_controller.rb, app/models/log_entry.rb, app/views/log/index.haml, coverage/.last_run.json, db/seeds.rb
=> Paginate teh dispatch log

app/assets/stylesheets/passengers.scss, app/controllers/mobility_devices_controller.rb, app/controllers/users_controller.rb, app/views/layouts/application.html.haml
=> Warn when you can't delete things

app/controllers/passengers_controller.rb, app/views/passengers/_form.html.haml, coverage/.last_run.json, spec/features/passenger_management_spec.rb
=> Don't initialize a doctor's note without an expiration date

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/datatables.scss, app/assets/stylesheets/jquery-ui.scss, app/assets/stylesheets/passengers.scss, app/assets/stylesheets/users.scss, package.json, yarn.lock
I think I found all the places where various asset libraries were circumvrenting the pipeline. These are all things that work in development, but don't work if you precompile assets.
=> Asset fixes

config/deploy.rb, config/deploy/production.rb
See https://github.com/umts/screaming-dinosaur/pull/94
=> Don't foward agent

app/assets/stylesheets/application.scss, app/views/passengers/_form.html.haml
=> Style links and buttons

db/migrate/20180914215234_set_passengers_active_default_true.rb, db/schema.rb
Closes #102.
Don't know why there was a collation difference.
=> Set active default on passengers

app/assets/javascripts/override_expiration.js, app/assets/stylesheets/passengers.scss, app/controllers/passengers_controller.rb, app/helpers/passengers_helper.rb, app/models/doctors_note.rb, app/views/passengers/_form.html.haml, app/views/passengers/index.haml, app/views/passengers/show.haml, config/locales/en.yml, coverage/.last_run.json, db/migrate/20190924150615_remove_override_from_doctors_notes.rb, db/schema.rb, spec/factories/doctors_notes.rb, spec/factories/passengers.rb, spec/features/passenger_key_spec.rb, spec/features/passenger_management_spec.rb, spec/helpers/passengers_helper_spec.rb
=> Remove override

app/assets/javascripts/datatables.js, app/assets/stylesheets/passengers.scss, app/helpers/passengers_helper.rb, app/views/passengers/index.haml, coverage/.last_run.json, db/seeds.rb, spec/features/passenger_filters_spec.rb, spec/helpers/passengers_helper_spec.rb
closes #96 
closes #58 
I didn't set out to fix these issues, but as I was working on another PR I got so pissed off about them that I got obsessed. It also got in the way of what I was working on, given that I'm making another page that includes a datatable.
=> Datatables fix

Capfile, config/deploy.rb
Whenever was removed in #127. So, this require didn't work.
=> Remove whenever config from Capistrano

db/migrate/20190924165620_add_active_status_data_to_passengers.rb
=> let migrations work with invalid data

app/views/passengers/_form.html.haml
=> forgot to account for nil

app/controllers/passengers_controller.rb, app/models/passenger.rb
=> Skip validations

Gemfile, Gemfile.lock, app/models/doctors_note.rb, app/models/passenger.rb, config/business_time.yml, config/initializers/business_time.rb, coverage/.last_run.json, spec/factories/doctors_notes.rb, spec/helpers/passengers_helper_spec.rb, spec/models/doctors_note_spec.rb, spec/models/passenger_spec.rb
closes #141 
This gem also handles holidays which is cool. It'll be more useful when #150 is merged.
=> add business day logic

app/assets/javascripts/application.js, app/assets/javascripts/datepicker.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/jquery-ui.scss, package.json, yarn.lock
* Removed jquery-datetimepicker
* Overrode sprite locations with ones that use Sprockets's `image-url`
* Also took the opportunity to remove JQueryUI CSS that we weren't using
=> Go back to (and fix) JQuery UI's datepicker

app/assets/stylesheets/application.scss
It was there in #151, which was a PR against #150. But, when #150 was merged, it was gone.
=> Restore datatables bootstrap theme

app/assets/stylesheets/application.scss, app/assets/stylesheets/font-awesome.scss
Oh, asset pipeline, when will you cease to vex me?
=> Fix fontawesome icons in production

app/controllers/log_controller.rb, app/models/user.rb, app/views/log/index.haml, coverage/.last_run.json, spec/models/user_spec.rb
=> Allow users to edit their own log entries

app/assets/stylesheets/application.scss, app/views/layouts/_navbar.haml, app/views/layouts/application.html.haml, app/views/log/index.haml, app/views/passengers/index.haml
While looking at #190, I found some other minor accessibility improvements to make.
=> A11y improvements

app/controllers/application_controller.rb
=> Limit the finding of the current user to active

app/pdfs/passengers_pdf.rb
- Closes #176 
- Removed the tabloid layout from the PDF and added a header to the table…s after the start of every new page.
=> Passenger PDF Layout changes

app/models/passenger.rb, spec/system/passenger_management_spec.rb
it has been verified that no existing active passengers have blanks in these fields.
=> make phone and address required for passengers.

app/models/passenger.rb, config/locales/en.yml, coverage/.last_run.json, spec/system/passenger_archive_spec.rb
Rubocop Passenger model and move things around a tiny bit.
=> Cleanup passenger model

app/controllers/application_controller.rb, app/controllers/feedback_controller.rb, app/controllers/log_controller.rb, app/controllers/passengers_controller.rb, app/controllers/sessions_controller.rb, coverage/.last_run.json
in preparation for ability to log in as a passenger.
=> add more granular restrictions.

app/controllers/passengers_controller.rb, app/models/passenger.rb, app/views/passengers/_form.html.haml, app/views/passengers/show.haml, coverage/.last_run.json, db/migrate/20200421183705_remove_status_from_passengers.rb, db/schema.rb, spec/system/passenger_management_spec.rb
Not sure why coverage went down, reviewing that now.
=> remove umass status from passenger

app/controllers/application_controller.rb, config/initializers/new_framework_defaults_5_2.rb
Should be safe to toggle all of these at this point
=> Switch on all of the Rails 5.2 defaults

app/controllers/mobility_devices_controller.rb, app/controllers/users_controller.rb, app/views/sessions/unauthenticated.haml, coverage/.last_run.json, spec/controllers/passengers_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/support/user_login_helpers.rb, spec/system/carriers_management_spec.rb, spec/system/passenger_registration_spec.rb, spec/system/user_management_spec.rb
Also the MobilityDevicesController.
Also while I was here:
* Wrote a controller spec to make sure of it
* A quick cleanup of the sessions/unauthenticated view
* Some other misc spec cleanup
=> Limit the UsersController to admin users

config/initializers/content_security_policy.rb
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
=> Enable CSP header

Gemfile, Gemfile.lock, app/assets/javascripts/log.coffee, app/assets/javascripts/log.js, app/views/log/index.haml
Also, while checking my one conversion, discovered that log submission was broken. Fixed.
=> Removed coffeescript

app/controllers/passengers_controller.rb
Trying to ease up on the perceived complexity of the `create` and `update` actions.
Abstracted out the "try to do the thing, rescue email errors" functionality.
=> Combine email failure rescuing

app/controllers/log_controller.rb
If it doesn't exist anymore, I think a 404 is reasonable.
Closes #227
=> Fix for deleting an already deleted log entry

app/views/feedback/new.haml
=> Warn not to include employee/pax info in feedback

app/views/passengers/_form.html.haml
Removed the 'permanent' checkbox for passenger registration. Closes #285
=> Removed permanent checkbox

package.json, yarn.lock
(In order to release a dependency on a vulnerable version of datatables.net)
=> Update datatable libraries

app/views/passengers/brochure.html.haml
=> Update Brochure Header

app/views/passengers/brochure.html.haml
=> Update Supervisor Names

app/views/passengers/brochure.html.haml
=> Reducted => Reduced

app/controllers/application_controller.rb, app/views/sessions/subsidiary.html.haml
=> Add view for subsdiary accounts

.gitignore, spec/spec_helper.rb
So that `--only-failures` works
=> Persist RSpec example status

.haml-lint.yml, Gemfile, Gemfile.lock
=> Add haml-lint

.gitignore
=> Remove old "data" directory

.gitignore, config/deploy.rb, db/migrate/20230222164919_add_uid_and_net_id_to_user.rb, db/migrate/20230222200720_add_uid_and_net_id_to_passenger.rb, db/schema.rb, lib/tasks/passengers.rake, lib/tasks/users.rake
Also added a CSV export for User and Passenger Spire IDs.
Not my favorite solution, but it turns out that it's going to be bureaucratically easier to use some domain-connected computer to do the NetID lookups. So the next step after this it to write some PowerShell :vomiting_face:.
=> Add NetID/UID for eventual Azure Auth

contrib/spire-lookup.ps1, lib/tasks/passengers.rake, lib/tasks/users.rake
Also, fixed export tasks to account for blank Spire IDs.
=> Powershell script for Spire lookup

app/models/passenger.rb, app/models/user.rb
=> Add inverse relation on users for Passenger#registerer

.rubocop.yml, Gemfile, Gemfile.lock, spec/controllers/passengers_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/helpers/passengers_helper_spec.rb, spec/libraries/passenger_param_manager_spec.rb, spec/mailers/passenger_mailer_spec.rb, spec/models/eligibility_verification_spec.rb, spec/models/feedback_spec.rb, spec/models/log_entry_spec.rb, spec/models/passenger_spec.rb, spec/models/user_spec.rb, spec/rails_helper.rb, spec/support/user_login_helpers.rb, spec/system/feedback_submission_spec.rb, spec/system/passenger_archive_spec.rb, spec/system/passenger_filters_spec.rb, spec/system/passenger_key_spec.rb, spec/system/passenger_management_spec.rb, spec/system/passenger_pending_spec.rb, spec/system/passenger_registration_spec.rb, spec/system/passenger_show_spec.rb, spec/system/user_management_spec.rb
=> Add rubocop-rspec

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/feedback_controller.rb, app/controllers/log_entries_controller.rb, app/controllers/mobility_devices_controller.rb, app/controllers/passengers_controller.rb, app/models/eligibility_verification.rb, app/models/feedback.rb, app/models/log_entry.rb, app/models/passenger.rb, app/models/user.rb, app/pdfs/passengers_pdf.rb, lib/tasks/passengers.rake, lib/tasks/users.rake, spec/controllers/passengers_controller_spec.rb
And made a `-a` and `-A` pass.
=> Added rubocop-rails

config/locales/en.yml
Should we just maybe just move this to the `User` model? Dunno.
=> New supervisors

Gemfile.lock
@aarinmehta is having trouble compiling due to openssl shenanigans - I believe this bump will allow him to build against 3
=> Bump mysql2

app/views/passengers/_filters_and_key.html.haml
=> Make export CSV button available to dispatchers

app/helpers/application_helper.rb, app/views/layouts/_navbar.haml, app/views/passengers/brochure.html.haml, app/views/passengers/brochure/_contacts.html.haml, app/views/passengers/brochure/_hours.html.haml, app/views/passengers/brochure/_policies.html.haml, app/views/passengers/brochure/_scheduling.html.haml, app/views/passengers/brochure/_welcome.html.haml, config/initializers/inflections.rb, config/locales/en.yml, spec/system/passenger_management_spec.rb
=> Brochure edits for AVS

Gemfile, Gemfile.lock, config/environments/production.rb
#487 caused... some sort of error in Uglifyer. Pretty hard to debug because of the nature of running JS in Ruby. Let's just bail on it.
=> Switch JS compresser to Terser

config/locales/en.yml
=> New contact email for AVS

app/assets/stylesheets/application.scss, app/assets/stylesheets/passengers.scss, app/helpers/passengers_helper.rb, app/views/passengers/_form.html.haml, app/views/passengers/brochure/_hours.html.haml
Based off #736
Mixed bag of stuff, mostly replacing stuff with built in bootstrap features.
=> Cut down on some unnecessary css

app/assets/stylesheets/application.scss, app/assets/stylesheets/passengers.scss, public/status_code.css
While I was working on the tooling, I realized that there were very few actual lints to fix here.
=> Fix style lints
